### ISSUE TITLE
Unable to install OKD on account that doesn't have access to gold images.

### ISSUE THREAD

**Issue by joshua-rutherford** [literalice/terraform-aws-openshift#12]
The `module.infra.aws_ami.commercial` data definition (https://github.com/literalice/terraform-aws-openshift/blob/master/modules/infra/ami.tf#L1) will fail if the AWS account does not have access to the RedHat Gold AMIs.  As per the resource documentation:

> If more or less than a single match is returned by the search, Terraform will fail.

 This should not be a requirement when installing OKD (i.e., when `use_community` is true).

**Comment by jasonmimick** [comment]
You can work around this by deleting the `module.infra.aws_ami.commercial` data definition

**Comment by joshua-rutherford** [comment]
@jasonmimick sure but the fix to make it optional was fairly trivial and has been merged.  Closing.
