### ISSUE TITLE
Found removed variables: openshift_node_kubelet_args is replaced by openshift_node_groups[<item>].edits;

### ISSUE THREAD

**Issue by dio** [literalice/terraform-aws-openshift#22]
Seems like this openshift_node_kubelet_args is removed. 

https://github.com/openshift/openshift-docs/issues/12623

**Comment by joshua-rutherford** [comment]
I just opened #24 which will remove them and thus get this working again but a better solution using the node group definitions may be more appropriate.

**Comment by literalice** [comment]
Thank you for reporting the issue and creating the PR.
I was able to reproduce the issue and confirm the fix.
